# code: language=ansible
---
- name: Basic install tasks
  hosts: workstation
  # connection: local
  become: true
  tasks:
    - name: Install multi python packages with version specifiers
      ansible.builtin.pip:
        name:
          - ansible-lint
        # set to absent since on python3.8 some issues occured.
        # WARNING: ansible-lint is no longer tested under Python 3.8 and will
        # soon require 3.9. Do not report bugs for this version.
        state: absent    # present, absent, latest, forcereinstall

    - name: Install pre-commit
      ansible.builtin.pip:
        name:
          - pre-commit

    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: install packages
      package:
        name:
          - htop
          # - tmux
          # - vim-nox

    - name: uninstall packages
      package:
        name:
          # - htop
          - tmux
          - vim-nox
        state: absent

    - name: Install tools
      apt:
        pkg:
          - software-properties-common
          - apt-transport-https
          - wget
        state: latest
        update_cache: true

- name: Install VSCode
  ansible.builtin.import_playbook: vscode.yaml

- name: Install Kind (k8s)
  ansible.builtin.import_playbook: kind.yaml
