# code: language=ansible
---
- name: My first play
  hosts: workstation
  #connection: local
  become: true
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

   - name: install packages
     package:
       name:
         - htop
         #- tmux
         #- vim-nox

   - name: uninstall packages
     package:
       name:
         #- htop
         - tmux
         - vim-nox
       state: absent

   - name: Install tools
     apt:
        pkg:
          - software-properties-common
          - apt-transport-https
          - wget
        state: latest
        update_cache: true
