# code: language=ansible
---
- hosts: workstation
  become: true
  roles:
    - base

- name: Install VSCode
  ansible.builtin.import_playbook: vscode.yaml

- name: Install Kind (k8s)
  ansible.builtin.import_playbook: kind.yaml
